### ISSUE TITLE
Python Linux egg install incomplete

### ISSUE THREAD

**Issue by j33433** [bgrimstad/splinter#103]
`python setup.py install` does not include the version file or .so file on Linux. The 'so' has to be loaded manually as result.

python 2.7.12
WSL with debian stretch/sid

**Comment by bgrimstad** [comment]
Hi. We are aiming to fix this and add PyPI support in v4.0. Note that the upcoming version does not support Python 2.

Please let us know if you are able to help us with this (see #44).

**Comment by gablank** [comment]
SPLINTER has now been uploaded to PyPI, and you can install it using `pip install splinterpy`.

Please note that the only operating system / architecture combination that is supported by the package at PyPI is Linux x64.
