### ISSUE TITLE
Mute python loading message

### ISSUE THREAD

**Issue by joshjchayes** [bgrimstad/splinter#112]
Hello again, 

Is there any way to mute the message which tells you where SPLINTER has been loaded from when you import splinter? We're using it in a forward-facing program and need to mute all printing out. Any chance you could move it into a module logger at DEBUG level? 

Message I am seeing:
In [1]: import exospy
Loaded SPLINTER from /Users/Josh/external_libraries/splinter/build/splinter-python/lib/osx/x86-64/libsplinter-3-0.dylib!

Thanks

**Comment by gablank** [comment]
Hello,

Unfortunately there's no flag for disabling that printout, but it will be removed in a later release. If you need to get rid of the message right now, I believe your options are either to capture stdout or to comment out the line in splinter.py.

Hope this helps!

**Comment by gablank** [comment]
Fixed in b2a1c888cc52d5cb69759751c37fa47cbfca9f26.
