### ISSUE TITLE
Python interface

### ISSUE THREAD

**Issue by bgrimstad** [bgrimstad/splinter#13]
Add Python interface for Python versions 2 and 3. Investigate if a single C interface may be used by both Python and MatLab.

**Comment by gablank** [comment]
This ended up being a lot of commits, but [this](149073cf22ff3dbc1d3d22165ef9eb329281de41) commit has a working Python interface.

I ended up using a single C interface for both MatLab and Python. There were some minor difficulties, such as MatLab storing Matrices in column-major order, but those have been worked around by adding a separate set of functions that accepts column-major data.
