### ISSUE TITLE
B-spline hessian

### ISSUE THREAD

**Issue by bgrimstad** [bgrimstad/splinter#14]
The Hessian of B-splines (BSpline) of all degrees seems to be wrong. It is not symmetrical over the diagonal. Test function: 4.5(x^4)-(x^3)+3(x^2)*y

**Comment by gablank** [comment]
550ab0cbbb81e2ac6869360a0996bcc80688a07b fixed symmetry

**Comment by gablank** [comment]
This issue may have been resolved by 550ab0cbbb81e2ac6869360a0996bcc80688a07b, and can be removed once #36 is implemented and the test confirms it.

**Comment by bgrimstad** [comment]
Hessian functionality was removed in f9df92421994b7a7a892f271267568e6c23d6c64 to simplify the interface and maintenance of SPLINTER. Hessian functionality may be reintroduced in a future version if it is in demand by users; please let us know what you think! 

All issues related to the Hessian functionality are closed for now.
