### ISSUE TITLE
Update MATLAB interface

### ISSUE THREAD

**Issue by bgrimstad** [bgrimstad/splinter#39]
Update class names in MATLAB interface and corresponding documentation.

**Comment by bgrimstad** [comment]
Consider removing DataTable (now named Sample) from the interface. Construction of an approximant would then look like Approximant(x, y, ...), where the matrix x and the vector y represents the sample inputs and outputs, respectively. In addition to simplifying the interface, this will enforce that all sample points are added in one batch. A drawback with removing Sample from the interface is that future operations related to shuffling and subdivision will not be available.

**Comment by gablank** [comment]
Fixed: 693f16833c688e3abb3436444ce69c2d13ba7f49
