### ISSUE TITLE
compiler error in psplineapproximant.cpp when building with asserts enabled

### ISSUE THREAD

**Issue by ds283** [bgrimstad/splinter#47]
I am seeing a compiler error when building SPLINTER in a debug configuration. The problem seems to be caused by the `assert()` on line 154 of psplineapproximant.cpp
```C++
for (unsigned int i=0; i < numVariables; i++)
{
    // Need at least three coefficients in each variable
    assert(basis.getNumBasisFunctions(i) >= 3);
}
```
The compiler reports that it cannot find the symbol `basis`
```
splinter/src/psplineapproximant.cpp:154:16: error: use of undeclared identifier 'basis'
        assert(basis.getNumBasisFunctions(i) >= 3);
```
and indeed I cannot see that `PSplineApproximant` or any of the classes it inherits from have such a member.

This seems to happen in both the master and development branches. Building with asserts disabled fixes the problem.

**Comment by gablank** [comment]
Hello @ds283!

Thanks for reporting this, this is indeed a bug. It's really weird that this bug hasn't caught our attention before, as we have been doing debug builds regularly while developing. We should probably reevaluate our release routines to avoid this happening again, especially since compilation errors are so easy (well, obviously not *that* easy) to detect and fix.

I'm currently testing a fix, will link it here when it's finished.

**Comment by gablank** [comment]
Okay, it seems I won't be able to push the fix today. Bjarne is about to modify the development branch quite a bit, so I am awaiting his changes before doing anything. The plan is to commit the fix to development, then cherry-pick the commit into master.

Or maybe committing the fix to master now, then merging master into development when it is ready is a better idea?

I am open for input, if you have any.

**Comment by ds283** [comment]
Thanks for all the feedback.

For me this isn't a major problem: although it's stopping debug builds, it's a trivial local change to comment out the `assert()` and wait for a fix to filter into development or master.

**Comment by gablank** [comment]
Just want to let you know that we have not forgotten this. We have been very busy lately, but plan to do some work on SPLINTER during the holidays around Christmas.

**Comment by bgrimstad** [comment]
This has now been fixed in the development branch. All assertions have been replaced with exceptions as requested by Issue #24.
