### ISSUE TITLE
Update to latest Eigen version

### ISSUE THREAD

**Issue by bgrimstad** [bgrimstad/splinter#53]
SPLINTER's Eigen should be updated to the latest stable version (currently Eigen 3.2.7). SPLINTER must compile on all supported platform for the change to be accepted.

Note: It seems like Eigen 3.3 is on the way and it may make sense to wait for the release of this version.

**Comment by gablank** [comment]
Delayed until Eigen 3.3 (which is currently in beta).

**Comment by bgrimstad** [comment]
Updated to Eigen 3.3.0 in e6f204cbb0254533c9855bab05f27aaa6ee19446. Compiles fine with GCC 4.8.3 on Linux. We must verify that it compiles on other platforms before preparing the next release.

**Comment by bgrimstad** [comment]
Updated to Eigen v3.3.4 in 5f5c8430eae236119f1c6f7e996d4fccce493725. 

Edit: See comment below.

**Comment by bgrimstad** [comment]
Updated to recent version 3.3.5 of Eigen to fix some compiler warnings. SPLINTER v4.0 will ship with this version.
