### ISSUE TITLE
Question about closest point

### ISSUE THREAD

**Issue by pmukherj** [bgrimstad/splinter#57]
Hey Guys, 

Love this library, and I'm still feeling my way around it. But what do you think would be the best way to find the closest point on the spline from an arbitrary point? Are there some specific functions that would help?

If this is something that I could implement, I would gladly PR it back in if y'all find it useful.

**Comment by bgrimstad** [comment]
Hi Prasenjit,

Happy to hear that you appreciate the library. We will shortly release a new major version that expands the interfaces towards C++, C, Python and Matlab. This will empower the users with regularization, amongst other things. 

Regarding your question about the closest point on the spline from an arbitrary point, or in other words, the minimum distance to the spline from a fixed point. You must first consider that, in general, the spline is a nonconvex function. Thus, the distance to the spline from a fixed point is most likely a nonconvex function. Let's say that the arbitrary point is [x*, y*] and the spline is parameterized as [x, f(x)]. Then your problem can be expressed as follows: min_x ||[x, f(x)] - [x*, y*]||, where ||z|| is some vector norm on a vector z. This is a nonconvex optimization problem, possibly with several local optima (several equally close points). Such problems require the application of a global optimization solver if you want a global optimum. It is a daunting task to venture into this topic, but if you desire to do so you can start by having a look at the global optimization solver for spline constraints (CENSO) in my repository (https://github.com/bgrimstad/censo). Beware that the documentation is somewhat outdated.

If you want a quick-and-dirty solution I would suggest the following algorithm (pseudocode):
```
dist = inf
for i = 1 to N
    Select starting point x' = x* + e, where e is a random number
    Do a local (Newton) search with the above objective function, starting at x'.
    Let found_distance be the local optimum.
    if found_distance < dist
        dist = found_distance
    end if
end for
return dist
```
The above algorithm is simply a multistart heuristic. Remember to use the gradients supplied by SPLINTER in the local search.

Good luck! And, please keep us updated on your progress.

Bjarne

**Comment by pmukherj** [comment]
Hey !
Thanks for the detailed answer and I figured this was a nonconvex problem! A CENSO connection is tempting but I'm having a good amount of luck with the more numerical approaches (including the one you suggested!). I was just wondering if there was something better.
In my case, I actually have a good guess of the point! So this makes it a little easier.  I'll see if I can package it (and what you suggested) in a logical unit that's usable by other splinter users.

**Comment by bgrimstad** [comment]
Very good. It sounds like a good solution for your problem.

We'll gladly review your code if you get time to package it as a pull request.
