### ISSUE TITLE
Expand BSpline interface

### ISSUE THREAD

**Issue by bgrimstad** [bgrimstad/splinter#58]
The following functions in BSpline should be made available in all interfaces:
std::vector< std::vector<double>> getKnotVectors() const;
DenseMatrix getControlPoints() const;
DenseVector getCoefficients() const;

**Comment by gablank** [comment]
e8c57d6a6b682b2fe39c8a30a504151ecbf522bf Updates the C and Python interfaces with this functionality.

**Comment by gablank** [comment]
Making a new issue that covers this: #62
