### ISSUE TITLE
By reference object passing

### ISSUE THREAD

**Issue by giorgiomarcias** [bgrimstad/splinter#64]
There are many functions that take/return big objects (like vectors) by value, causing to make temporary copy of such objects. Passing objects by (const) reference, instead, would increase performances a bit.

**Comment by gablank** [comment]
You are right, there is room for improvement when it comes to passing objects by const ref instead of by value as parameters to functions that don't need a copy of the object.

However, I believe we can rely on [return value optimization](https://en.wikipedia.org/wiki/Return_value_optimization) when returning large objects, unless there are cases where the optimization is not applicable (I'm not sure whether there is such a function in SPLINTER or not).

Thank you for taking the time to report this issue!

**Comment by bgrimstad** [comment]
Returning (const) references, rather than relying on return value optimization, would also make our intentions clearer. I am not aware of any functions that avoids this optimization by gcc, however, this uncertainty can also be removed by simply returning references. 

Please suggest which function signatures we should change to pass/return by const reference.

**Comment by giorgiomarcias** [comment]
Here is the list:

https://github.com/bgrimstad/splinter/blob/master/include/function.h#L49
https://github.com/bgrimstad/splinter/blob/master/include/function.h#L59
https://github.com/bgrimstad/splinter/blob/master/include/function.h#L77
https://github.com/bgrimstad/splinter/blob/master/include/function.h#L87
https://github.com/bgrimstad/splinter/blob/master/include/function.h#L90

https://github.com/bgrimstad/splinter/blob/master/include/datatable.h#L39
https://github.com/bgrimstad/splinter/blob/master/include/datatable.h#L40
https://github.com/bgrimstad/splinter/blob/master/include/datatable.h#L52 (could return const ref)

https://github.com/bgrimstad/splinter/blob/master/include/datapoint.h#L27
https://github.com/bgrimstad/splinter/blob/master/include/datapoint.h#L28
https://github.com/bgrimstad/splinter/blob/master/include/datapoint.h#L32 (could return const ref)
https://github.com/bgrimstad/splinter/blob/master/include/datapoint.h#L47
https://github.com/bgrimstad/splinter/blob/master/include/datapoint.h#L48
https://github.com/bgrimstad/splinter/blob/master/include/datapoint.h#L49

https://github.com/bgrimstad/splinter/blob/master/include/bsplinebuilder.h#L63
https://github.com/bgrimstad/splinter/blob/master/include/bsplinebuilder.h#L77

https://github.com/bgrimstad/splinter/blob/master/include/bsplinebasis1d.h#L43 (could return const ref)

https://github.com/bgrimstad/splinter/blob/master/include/bsplinebasis.h#L23
https://github.com/bgrimstad/splinter/blob/master/include/bsplinebasis.h#L34
https://github.com/bgrimstad/splinter/blob/master/include/bsplinebasis.h#L39 (could return const ref ? )
https://github.com/bgrimstad/splinter/blob/master/include/bsplinebasis.h#L41 (could return const ref)

https://github.com/bgrimstad/splinter/blob/master/include/bspline.h#L38
https://github.com/bgrimstad/splinter/blob/master/include/bspline.h#L39
https://github.com/bgrimstad/splinter/blob/master/include/bspline.h#L40
https://github.com/bgrimstad/splinter/blob/master/include/bspline.h#L60
https://github.com/bgrimstad/splinter/blob/master/include/bspline.h#L61
https://github.com/bgrimstad/splinter/blob/master/include/bspline.h#L62
https://github.com/bgrimstad/splinter/blob/master/include/bspline.h#L65
https://github.com/bgrimstad/splinter/blob/master/include/bspline.h#L66
https://github.com/bgrimstad/splinter/blob/master/include/bspline.h#L71 (could return const ref and made const)
https://github.com/bgrimstad/splinter/blob/master/include/bspline.h#L110
https://github.com/bgrimstad/splinter/blob/master/include/bspline.h#L116
https://github.com/bgrimstad/splinter/blob/master/include/bspline.h#L149

**Comment by gablank** [comment]
Thank you, Giorgio, we will definitely look into this.

**Comment by bgrimstad** [comment]
Thank you. We can safely do all the suggested pass-by-const-reference changes. I want to consider each return-by-reference case before we do those.

Giorgio, we would appreciate it if you prepared a pull request to the development branch in line with my comment above.

**Comment by giorgiomarcias** [comment]
Sure. I'll do it as soon as I can.

**Comment by gablank** [comment]
Thank you, Giorgio, we really appreciate you taking time out of your day to improve SPLINTER!

However, we would like to review the return-by-reference cases case by case to be absolutely sure that the changes doesn't have any unintended side effects, so we will have to do some testing before eventually merging your pull request.

We believe changing appropriate parameters to pass-by-const-ref will be fine, though, so if you want to make a pull request implementing that change too, we will be more than happy to merge it right away.

Thank you again for contributing and showing interest in our library, that is the sole reason we published it! If you find success in using SPLINTER in other projects, we would love to hear how that went.

**Comment by giorgiomarcias** [comment]
Here you are :-)
All the tests pass. I didn't changed/added any test, though, so please review these commits.

Thank you for your work! I'll let you know when my project is complete!

**Comment by bgrimstad** [comment]
Closing this now. We can create a new issue if we decide to undertake further optimizations.

Thank you.
