### ISSUE TITLE
Type hinting breaks Python 2

### ISSUE THREAD

**Issue by gablank** [bgrimstad/splinter#71]
Example where type hinting is used: https://github.com/bgrimstad/splinter/blob/d393fb26900d659e91cf3c88bce8aa73675f1eba/python/splinter/bspline.py#L31

Unsure what the best way of proceeding here. Some options:
- Discontinue support for Python 2 (bad idea?)
- Remove type hinting
- Duplicate files: One for 2 and one for 3?

Surely someone must've encountered this issue before us, so some research into other solutions should be well worth the effort.

**Comment by bgrimstad** [comment]
We will prepare release 3.1 with support for Python 2 and 3. Support for Python 2 will then be discontinued, meaning that later releases will support only Python 3.

**Comment by bgrimstad** [comment]
Considering this issue stale and will proceed to close. 

Note that Release 3.1 was never prepared for Python 2 due to lack of interest. Newer releases will use Python 3.5+.
