### ISSUE TITLE
splinter-3.0-py3.5.egg dissapears during Ubuntu install

### ISSUE THREAD

**Issue by exook** [bgrimstad/splinter#73]
Hi, I've been trying for a good while to get Splinter 3.0 to work. But when in teh python folder try to run "python3 setup.py install"  I get the final prompt:

"Installed /usr/local/lib/python3.5/site-packages/splinter-3.0-py3.5.egg
Processing dependencies for splinter==3.0
Finished processing dependencies for splinter==3.0"

But when going to "/home/usr/.local/lib/python3.5/site-packages" the folder is empty. When trying to import splinter in a script i get an error saying that it failed to import splinter.

Best regards,

**Comment by gablank** [comment]
Hello @exook,

The Python install script does not work currently with SPLINTER. At the end of [this](https://github.com/bgrimstad/splinter/blob/dad6476dd279a9dd46d029a7a35ee61376c54380/docs/compile.md#compile-on-unix-tested-with-ubuntu) guide, after then `make install` step, you should have a directory called splinter-python containing the Python files.

Implementing a proper setup.py is on our (mine, especially) todo-list, but there are often too few hours in the day.
