### ISSUE TITLE
Compilation issue Linux

### ISSUE THREAD

**Issue by exook** [bgrimstad/splinter#74]
Hi, when completing the final step of the compilation using "./scripts/build_release.sh" I've been prompted with:

"Cannot make release because an OS directory (windows) is missing."

This happened both on a windows/Ubuntu dual boot and a pure Linux computer, I cannot seem to find a solution to this issue.

Best regards,
Alex

**Comment by gablank** [comment]
Hello @exook,

That last failing step is not necessary for the compilation to complete. The script is used by me when we make a new release of SPLINTER, and the last step is only for packaging all the versions.

You should be able to find the compiled library in build/OS/COMPILER/ARCHITECTURE.

If this does not work, maybe you could try following [this](https://github.com/bgrimstad/splinter/blob/dad6476dd279a9dd46d029a7a35ee61376c54380/docs/compile.md#compile-on-unix-tested-with-ubuntu) guide?

Sorry you're having problems, maybe we should change build_release.sh to only optionally perform the last step.

Anders.

**Comment by bgrimstad** [comment]
Beware @exook, 

If you intend to use SPLINTER with Anaconda you should compile with gcc version 4.4-4.8. 

Presuming you are using Ubuntu 16.04, which ships with gcc 5 and 6, you will have to install gcc 4.8 (or earlier version). You can then select which compiler to use by adding the following line to CMakeLists.txt:
`set(CMAKE_CXX_COMPILER /usr/bin/g++-4.8)`

**Comment by exook** [comment]
Thank you both for the replies! I really appreciate it. The Advanced compile guide worked. For step 4 i used >CXX=$(which g++-4.8")< instead of >CXX=$(which g++)<. I made the change to CMakeList.txt. After the build, my path looked like >/home/usr/Desktop/splinter/build/splinter-python/python< so there is no sign of >/OS/<. In that path i then ran >sudo python3 setup-py install and i got three new folders build, dsit and splinter.egg-info. After that I opened Spyder and opened the examples. After changeing >splinter.load("/home/anders/SPLINTER/build/debug/libsplinter-3-0.so")< to my current path >/home/usr/Desktop/splinter/build/libsplinter-3-0.so< they all worked wonderfully! Thank you both for the quick and really helpful replies, I'm looking forward to what Splinter can bring to my work!

Best,
Alex

**Comment by gablank** [comment]
Thanks for your feedback, I'm happy to hear you got it working. It seems our build system could use some work, we should make it easier to compile and use SPLINTER.

If you don't mind me asking, what are you planning to use SPLINTER for? There's few things more rewarding than hearing that someone got good use out of it :)

Anders.

**Comment by exook** [comment]
I'm currently doing physics research and we have some data which is not well fitted by other methods at higher values where the uncertainties become larger. My supervisor found Splinter and thought it would be a quick and easy way to get good fits to our data.
