### ISSUE TITLE
B-spline how to add control points?

### ISSUE THREAD

**Issue by KahnShi** [bgrimstad/splinter#75]
Hi guys,

I want to build non uniform spline using knots and control points. 
I carefully read the [cpp interface of splinter](https://github.com/bgrimstad/splinter/blob/master/docs/cpp_interface.md), but I do not totally understand how to add these basic values.
Could you give me any hint?

Thx!
Kahn

**Comment by gablank** [comment]
Hello Kahn,

You need to use [this constructor](https://github.com/bgrimstad/splinter/blob/dad6476dd279a9dd46d029a7a35ee61376c54380/include/bspline.h#L39). Please note that the first parameter (coefficients) is not exactly the same as control points, but they are related.

Thank you for showing interest in SPLINTER!

Anders.

**Comment by bgrimstad** [comment]
Hello,

To supplement what @gablank already said: the current version of SPLINTER only supports 1-D control points, which we refer to as coefficients. Furthermore, control point weighting, as used in NURBS, is not yet supported. We have plans to support both features in version 4.0. An update to the documentation is also much needed.

Bjarne

**Comment by KahnShi** [comment]
Hi Anders and Bjarne,

Thank you for your kind help and detailed explanation.
Btw, could I ask what is the coefficients in your system? What is the difference with control point?

Kahn

**Comment by bgrimstad** [comment]
Hi Kahn,

Our 'coefficients' are 1-D control points. However, several places in our code we refer to a control point as the vector (u_i, c_i), where u_i is the i-th knot average and c_i is the i-th 'coefficient'. I understand that this is confusing. I created a new branch today in which I will rename 'coefficients' to 'control points' and also allow for multi-dimensional control points. 

PS: Meanwhile, if you need multi-dimensional control points you may create a set of B-splines (one for each output).

**Comment by KahnShi** [comment]
Hi Bjarne,

Thank you very much for your efforts.
I will have a try.

Kahn
