### ISSUE TITLE
Derivative of the interpolated function

### ISSUE THREAD

**Issue by oguzumut-cnrs** [bgrimstad/splinter#84]
Hi,
After I perform spline interpolation, is there a way to evaluate the derivative of the interpolated function ?

Thanks

**Comment by gablank** [comment]
Hello,

Yes, you can use Function::evalJacobian, which returns a vector of the same dimension as the input. If your function is one-dimensional, then the vector returned from that function will be one-dimensional, with the only element equal to ```f'(x)```. If the input has more than one dimension, then the output will be the partial derivatives of the function.

**Comment by oguzumut-cnrs** [comment]
Hi,

Thanks a lot. However, I noticed that you use finite differences to evaluate the derivatives 
(if I understood correctly). Why not use the analytical derivative of the spline?

**Comment by bgrimstad** [comment]
Hi,

We actually provide analytical derivatives for B-splines; if you look in bspline.h you will find that BSpline::evalJacobian overrides Function::evalJacobian. We use the finite differences mainly for testing purposes.

**Comment by oguzumut-cnrs** [comment]
Hi,

OK thanks. 

It could be great if interpolation results could be saved so that we won't need to re-perform calculations for the same data each time. In physics, very complicated analytical formulae for atomistic energies have been replaced by a set of discrete values written on text files, from which we interpolate and replace the analytical function. 

Thanks

**Comment by oguzumut-cnrs** [comment]
Well, it is already done 👍 
	const char *fileName = "test.bspline";
        bspline3.save(fileName);
        BSpline loadedBSpline(fileName);

Great library.

**Comment by bgrimstad** [comment]
Thank you. 

If you are using the multidim-control-points branch you may also use BSpline::save_to_json which stores the B-spline parameters in a human readable format. The json format should also be version-agnostic, which is not the case for the current binary format in BSpline::save. Please be aware of this if you upgrade to a newer version of SPLINTER in the future.

**Comment by oguzumut** [comment]
Hello,

I am having an error while evaluating the hessian using the command evalHessian. The error message is: terminating with uncaught exception of type std::bad_alloc: std::bad_alloc.

evaljacob works perfectly fine.

Are you aware of any issues? 

Regards
