### ISSUE TITLE
Drawing a Bezier curve

### ISSUE THREAD

**Issue by wiltchamberian** [bgrimstad/splinter#86]
DataTable samples.
samples.addSample(x1,y1);
samples.addSample(x2,y2);
...
BSpline bspline = BSpline::Builder(samples).degree(2).build();
when xi==xj ,it will throw an exception,but a BezierCurve should be Constructed when xi==xj,
such as some points on a circle which radius is 10,center is(0,0) 
then (0,-10),(0,10) are in the samples,

**Comment by bgrimstad** [comment]
Hello,

When drawing Bezier curves it is common to parameterize a B-spline f : R -> R^2 with a single variable 0 <= t <= 1. The points you refer to as (x1, y1), (x2, y2), etc., will then act as 2-D control points. 

This Python example shows you how to draw a Bezier curve using SPLINTER: https://github.com/bgrimstad/splinter/blob/multidim-control-points/python/examples/bspline_picassos_dog.py

Hope that was clarifying.

Bjarne
