### ISSUE TITLE
3D curve fitting exist? & 2D fitting problem

### ISSUE THREAD

**Issue by putine** [bgrimstad/splinter#99]
Is that possible to use splinter to smooth a 3D curve(point cloud)?
 I also found that in 2D situation, if sample points are "too orthogonal" to x-axis, then, the smoothing effect using p-spline mode  seems not good. 
And in 2D, the order of points seem to be sorted by x value, is it better to let the user give the order of points? Or create a new method to let user to do this?

**Comment by bgrimstad** [comment]
Hi, 

In v3.0 you may fit any f : R^m -> R spline to data on a regular grid. 

In the upcoming release, you can fit any f : R^m -> R^n spline to data. The spline can fit to a point cloud, but you will need to manually select knot vectors to obtain a sufficient/meaningful model flexibility. This may be a challenging task and unless you require a B-spline function, there may exist other regression methods that are better suited for you problem, e.g. a neural network.

It is correct that the order of points are sorted by coordinate values in v3.0. We are planning to change the order to the one given by the user. See #95.

Regards, 
Bjarne
